import React, { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Rect, Text as SvgText } from 'react-native-svg';
import Button from '../components/Button'; import { AppProject, AppScreen, CropBox } from '../types'; import { sortReadingOrder } from '../utils/naming';
export default function SheetEditorScreen({ project, setProject, upsertCrop, removeCrop, go }: { project: AppProject; setProject: React.Dispatch<React.SetStateAction<AppProject>>; upsertCrop:(c:CropBox)=>void; removeCrop:(id:string)=>void; go:(s:AppScreen)=>void }) {
 const [start,setStart]=useState<{x:number;y:number}|null>(null); const [draft,setDraft]=useState<CropBox|null>(null); const sheet=project.sourceSheet;
 if(!sheet) return <View style={styles.wrap}><Text style={styles.title}>Sheet Editor</Text><Text style={styles.note}>Import a sheet first.</Text><Button title="Import" onPress={()=>go('import')} /><Button title="Back" onPress={()=>go('home')} secondary /></View>;
 const sx=360/sheet.width; const sy=520/sheet.height; const scale=Math.min(sx,sy); const w=sheet.width*scale; const h=sheet.height*scale;
 const toImg=(e:any)=>({x:e.nativeEvent.locationX/scale,y:e.nativeEvent.locationY/scale});
 const finish=()=>{ if(draft && draft.width>8 && draft.height>8) upsertCrop(draft); setStart(null); setDraft(null); };
 const autoDetect=()=>{ const cols=3, rows=3, margin=20; const cw=(sheet.width-margin*2)/cols, ch=(sheet.height-margin*2)/rows; const crops:Array<CropBox>=[]; for(let y=0;y<rows;y++) for(let x=0;x<cols;x++) crops.push({id:`auto_${Date.now()}_${x}_${y}`,order:crops.length+1,x:margin+x*cw,y:margin+y*ch,width:cw*0.82,height:ch*0.82,category:'base'}); setProject(p=>({...p,crops:sortReadingOrder(crops)})); };
 return <View style={styles.wrap}><Text style={styles.title}>Sheet Editor</Text><Text style={styles.note}>Drag on the sheet to create crop boxes. Tap a box to delete it; adjust precisely in Asset List.</Text><Pressable style={[styles.stage,{width:w,height:h}]} onPressIn={e=>{const p=toImg(e); setStart(p); setDraft({id:`crop_${Date.now()}`,order:project.crops.length+1,x:p.x,y:p.y,width:1,height:1,category:'base'});}} onPressOut={finish} onTouchMove={e=>{ if(!start)return; const p=toImg(e); setDraft(d=>d&&({...d,x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),width:Math.abs(p.x-start.x),height:Math.abs(p.y-start.y)})); }}><Image source={{uri:sheet.uri}} style={{width:w,height:h}} resizeMode="contain" /><Svg style={StyleSheet.absoluteFill}>{[...project.crops,draft].filter(Boolean).map((c:any)=><React.Fragment key={c.id}><Rect x={c.x*scale} y={c.y*scale} width={c.width*scale} height={c.height*scale} stroke="#43d9ad" strokeWidth="2" fill="rgba(67,217,173,0.12)" onPress={()=>removeCrop(c.id)} /><SvgText x={c.x*scale+6} y={c.y*scale+18} fill="#fff" fontWeight="bold">{c.order}</SvgText></React.Fragment>)}</Svg></Pressable><Button title="Auto detect assets" onPress={autoDetect} secondary /><Button title="Asset list & names" onPress={()=>go('assets')} /><Button title="Back" onPress={()=>go('home')} secondary /></View>;
}
const styles=StyleSheet.create({wrap:{flex:1,padding:16},title:{color:'#fff',fontSize:28,fontWeight:'800'},note:{color:'#9fb0c4',marginVertical:8},stage:{alignSelf:'center',backgroundColor:'#05070a',overflow:'hidden',borderRadius:12,borderColor:'#27364a',borderWidth:1}});
